# Numpy

It is the fundamental package for sicentific computing with pythong. 

it offers:- 

- Powerful N-dimensinoal arrays
- It offers numerical computing tools.
- It is open source under BSD license.
- It is interoperable with a variety of hardware and computing systens.
- It is performant with it swell optimized C code. bring sthge fliexibility of python and the speed of C.
- it is easy to use because of its high level syntax, making it accessible with minimal learning curve. 

## numpy ecosystem

- Scientific domains
  - Quantum computing
  - Statistical computing
  - signal processing
  - image processing
  - graphs and networks
  - astronomy
  - cognitive psychology
  - bioinformatics
  - bayesian inference
  - mathematical analysis
  - chemistru
  - geoscience
  - geographic processing
  - architecture & engineering
- Array Libraries
  - Dask
  - CuPy
  - JAX
  - Xarray
  - sparse
  - pytorch
  - tensorflow
  - arrow
  - xtensor
  - awkward array
  - uarray
  - tensorly
- Data Science
  - ETL
  - exploratory analysus
  - model and evaluate
  - reprot in a dashboard
- Machine Learning
  - Scikit-learn
  - SciPy
  - Tensorflow
  - PyTorch
  - XGBoost
  - LightGBM
  - CatBoost
  - Yellowbrick
  - Eli5
- Visualization
  - matplotlib
  - seabor
  - plotly
  - altari
  - bokeh
  - holoviz
  - vispy
  - napari
  - pyvista

for more info:- https://numpy.org (scroll down)

## Absolute basics

NumPy stands for Numerical Python. It is an open source python library that is widely used in science and engineering.

it contains multidimensional array data structures, such as the homogenous N-deimensional ndarray and a large library of functions that operate efficiently on these data structures. 

While python lists are good general purpose homogenouys containers, but for data with certain cahracteristics , it may not be the most appropriate. 

for some operationsf and datay, other containers maybe more appropriate. by exploiting these, we can improve spee,d reduce memory consumption and offer a high-level syntax for pefroming a variety of common processing tasks. The benefits of NumPy become more apparent when there a relage quantities of homogenous data to be processed on the same CPU




with an array being a contigous gird of data, a ndomenional array is an array of arbitariy dimensions, consisting of lower-dimensional arrays stacked, as though they are on separate pages. 

Restrictions on data when dealing with numpy arrays:- 
1) all elements of the array msut be of the same type of data.
2) once creted the total size of the aray cant change
3) the shape msut be rectangular, not jagged.

when these conditions are met, numpy levarages these characteristics to make the array faster, more memory efficient. 


In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
b = np.array((1,2,3,4,5))
b

array([1, 2, 3, 4, 5])

In [4]:
a[0] = 0
a

array([0, 2, 3, 4, 5])

In [5]:
a[:3]

array([0, 2, 3])

one major differnece between slice indexing of python list and that of array is that, slice indexing of a list copies the elements into a new list, but slicing an arary returns a view. 
a view is an object thaqt refers to the data in the original array. the original aray can be mutated vusing the view. 

In [6]:
a = [1,2,3,4]
a

[1, 2, 3, 4]

In [7]:
b = a
b

[1, 2, 3, 4]

In [8]:
b[0] = 0
b

[0, 2, 3, 4]

In [9]:
a

[0, 2, 3, 4]

In [10]:
b = a[:]
b

[0, 2, 3, 4]

In [11]:
b[0] = 1
b

[1, 2, 3, 4]

In [12]:
a

[0, 2, 3, 4]

In [13]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [14]:
b = a
b

array([1, 2, 3, 4])

In [15]:
b[0] = 0
b

array([0, 2, 3, 4])

In [16]:
a

array([0, 2, 3, 4])

In [17]:
b = a[:]
b

array([0, 2, 3, 4])

In [18]:
a

array([0, 2, 3, 4])

In [19]:
b[0] = 1
b

array([1, 2, 3, 4])

In [20]:
a

array([1, 2, 3, 4])

as seen above, slicing returned a view, that refers to the dat in the original array. the original array can be mutated with the view. but in regular python lists, slicing returns a completely new list, into which elements are copied into. 

Higher dimensional arrays can be initialized from nested python sequences. 

In numpy a dimensoin of an array is referred to as an axis. 


In [21]:
def info(a):
    print(f"Array: \n{a}")
    print(f"Shape: {a.shape}")
    print(f"Number of Dimensions: {a.ndim}")
    print(f"Data Type: {a.dtype}")

In [22]:
a.ndim

1

In [23]:
a = np.array([[i for i in range(1,5)] for j in range(1,5)])
a

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [24]:
a.ndim

2

In [25]:
a = np.array([[[1]]])
a

array([[[1]]])

In [26]:
a.ndim

3

In [27]:
a.shape

(1, 1, 1)

In [28]:
a = np.array([[[1,1]]])
a

array([[[1, 1]]])

In [29]:
a.ndim


3

In [30]:
a.shape

(1, 1, 2)

In [31]:
a[0]

array([[1, 1]])

In [32]:
a[0][0]

array([1, 1])

In [33]:
a

array([[[1, 1]]])

In [34]:
a = np.array([[1,1],[1,1]])
a

array([[1, 1],
       [1, 1]])

In [35]:
a.shape

(2, 2)

In [36]:
a.ndim

2

In [37]:
a = np.array([[[1,1],[1,1]]])
a

array([[[1, 1],
        [1, 1]]])

In [38]:
a.shape

(1, 2, 2)

In [39]:
a.ndim

3

In [40]:
info(a)

Array: 
[[[1 1]
  [1 1]]]
Shape: (1, 2, 2)
Number of Dimensions: 3
Data Type: int64


In [41]:
a = np.array([[1,1],[1,2]])
info(a)

Array: 
[[1 1]
 [1 2]]
Shape: (2, 2)
Number of Dimensions: 2
Data Type: int64


so, the flow goes as follows: - element in a column, elements in a row, row in rows of rows, rows of rows in matrix, 
matrices in rows of matrices. 

so the number of dimensions can the thought of the number of nestings

In [42]:
a = np.array([[[[[1,2]],[[3,4]]]]])
info(a)

Array: 
[[[[[1 2]]

   [[3 4]]]]]
Shape: (1, 1, 2, 1, 2)
Number of Dimensions: 5
Data Type: int64


### creating basic arrays:- 

In [45]:
a = np.zeros((2,3))
info(a)

Array: 
[[0. 0. 0.]
 [0. 0. 0.]]
Shape: (2, 3)
Number of Dimensions: 2
Data Type: float64


In [49]:
b = np.ones((2,2,2,2,))
info(b)

Array: 
[[[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]]
Shape: (2, 2, 2, 2)
Number of Dimensions: 4
Data Type: float64


In [52]:
np.empty((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [54]:
for i in range(3):
    print(info(np.ones((i,i,i))))

Array: 
[]
Shape: (0, 0, 0)
Number of Dimensions: 3
Data Type: float64
None
Array: 
[[[1.]]]
Shape: (1, 1, 1)
Number of Dimensions: 3
Data Type: float64
None
Array: 
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
Shape: (2, 2, 2)
Number of Dimensions: 3
Data Type: float64
None


In [67]:
a = np.arange(1,9)
info(a)

Array: 
[1 2 3 4 5 6 7 8]
Shape: (8,)
Number of Dimensions: 1
Data Type: int64


In [68]:
a.reshape((1,1,8))

array([[[1, 2, 3, 4, 5, 6, 7, 8]]])

In [78]:
from itertools import permutations

def reshape_combinations(arr):
    n = arr.size
    
    # Iterate over possible values of a
    for a in range(1, int(n ** (1/3)) + 1):
        if n % a == 0:  # a must divide n
            n_a = n // a  # Reduce n by a
            # Iterate over possible values of b
            for b in range(1, int(n_a ** 0.5) + 1):
                if n_a % b == 0:  # b must divide n/a
                    c = n_a // b  # c is determined by a and b
                    if a * b * c == n:
                        # Generate all permutations of (a, b, c)
                        perms = permutations((a, b, c))
                        for perm in perms:
                            info(arr.reshape(perm))

In [79]:
reshape_combinations(a)

Array: 
[[[1 2 3 4 5 6 7 8]]]
Shape: (1, 1, 8)
Number of Dimensions: 3
Data Type: int64
Array: 
[[[1]
  [2]
  [3]
  [4]
  [5]
  [6]
  [7]
  [8]]]
Shape: (1, 8, 1)
Number of Dimensions: 3
Data Type: int64
Array: 
[[[1 2 3 4 5 6 7 8]]]
Shape: (1, 1, 8)
Number of Dimensions: 3
Data Type: int64
Array: 
[[[1]
  [2]
  [3]
  [4]
  [5]
  [6]
  [7]
  [8]]]
Shape: (1, 8, 1)
Number of Dimensions: 3
Data Type: int64
Array: 
[[[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]

 [[7]]

 [[8]]]
Shape: (8, 1, 1)
Number of Dimensions: 3
Data Type: int64
Array: 
[[[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]

 [[7]]

 [[8]]]
Shape: (8, 1, 1)
Number of Dimensions: 3
Data Type: int64
Array: 
[[[1 2 3 4]
  [5 6 7 8]]]
Shape: (1, 2, 4)
Number of Dimensions: 3
Data Type: int64
Array: 
[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
Shape: (1, 4, 2)
Number of Dimensions: 3
Data Type: int64
Array: 
[[[1 2 3 4]]

 [[5 6 7 8]]]
Shape: (2, 1, 4)
Number of Dimensions: 3
Data Type: int64
Array: 
[[[1]
  [2]
  [3]
  [4]]

 [[5]
  [6]


In [83]:
a = np.linspace(0,10,num = 5)
info(a)

Array: 
[ 0.   2.5  5.   7.5 10. ]
Shape: (5,)
Number of Dimensions: 1
Data Type: float64
